# specify which platform the app is built for
language: node_js

# specify which version of the specifed platform should Travis use
# Since our version on node (4.8.0) is only supported by Travis vis nvm,
# so, we have specified the node version separately in .nvmrc in project root
#node_js: 4.8.0

# Since we're using yarn for package management, we can tell Travis to cache 
# the installed yarn packages/files so that repeat builds are faster
cache: yarn

# Overide the default Travis behaviour of running npm test as the 
# main build script
script: npm run build

deploy:
  provider: releases
  api_key: $GITHUB_PERSONAL_ACCESS_TOKEN
  file: ${TRAVIS_BUILD_DIR}/${TRAVIS_REPO_SLUG}-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true